name = "1 . 20 . 1 Modpack"
author = "Just8It"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88dad506939c2468c2fa15a5a2ded7a4e117d69bcb771246958cf0e2c3ea99c8"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
