name = "1 . 20 . 1 Modpack"
author = "Just8It"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cdd3064ad821e3c4f2d85861f7ea795b4696aa7d9f5ad917d8e30fdbb2cdf27"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
