name = "1 . 20 . 1 Modpack"
author = "Just8It"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2025ec0cee010ae8ede4bf6d9077e3183fad6f3f2da0f6c619b81423f5e007a0"

[versions]
forge = "47.1.44"
minecraft = "1.20.1"
