name = "1 . 20 . 1 Modpack"
author = "Just8It"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d80945c34f4b6cb61141a3018f9255b333e160aa24e48bbf43af58560b70d2ac"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
