name = "1 . 20 . 1 Modpack"
author = "Just8It"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bbe17113abf24452de4714fa7aac4412cdcd20c424d33a131f6a62c11e3ee1a"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
