name = "1 . 20 . 1 Modpack"
author = "Just8It"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b31ce7a33207a59a69f370a2e98848df42136b6548478d0f6b7b3c7ced16f9c8"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
